version: '3'

services:

  app:
    image: chembience/wagtail-cms:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience-wagtail-cms
    volumes:
      - "${DJANGO_APP_HOME}:/home/app"
      - "${CHEMBIENCE_HOME}:/home/sphere"
      - "${CHEMBIENCE_SHARE}:/home/share"
    ports:
       - "${DJANGO_APP_CONNECTION_PORT}:80"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
    depends_on:
      - proxy
      - cmsdb
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]

  proxy:
    image: chembience/proxy:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CHEMBIENCE_SPHERE}:/home/sphere"
    ports:
      - "${PROXY_EXTERNAL_PORT}:80"
    networks:
      - sphere

  cmsdb:
    image: chembience/db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience-cmsdb
    volumes:
      - cmsdb_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_DB_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_DB_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  cmsdb_volume:

networks:
  sphere:
